server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hamcam?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: merk
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  sql:
    init:
      encoding: UTF-8

  mail:
    host: smtp.naver.com
    port: 465
    username: nskfn02@naver.com
    password: QLGVFX36FNC3
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com

  data:
    redis:
      host: localhost
      port: 6379

  web:
    resources:
      static-locations: file:C:/FinalProject/uploads
      add-mappings: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  ai:
    openai:
      api-key: AIzaSyAnMziLv24BNczctq-J1k-fjH8sqalPKIk

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

livekit:
  api-key: 878de0038dbed61ed7daab9872fed4e2017e1a37a0b12038a1d62573b64cb4bc
  api-secret: 878de0038dbed61ed7daab9872fed4e2017e1a37a0b12038a1d62573b64cb4bc
  ws-url: ws://localhost:7880
  ttl-minutes: 60 