server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hamcam?useSSL=false&serverTimezone=UTC  # MySQL 접속 URL
    username: root  # MySQL 사용자명 입력
    password: elskvhfh12  # MySQL 비밀번호 입력
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC 드라이버

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Hibernate의 MySQL 8 Dialect 사용
    hibernate:
      ddl-auto: update  # 개발 시 update, 운영 환경에서는 none 또는 validate 권장
    properties:
      hibernate:
        format_sql: true  # SQL 보기 편하게 포맷
        show_sql: true  # SQL 실행문 로그 출력

  session:
    store-type: redis
    redis:
      namespace: spring:session
      flush-mode: on_save
    timeout: 30m

  # ✅ 이메일 (네이버 SMTP 사용)
  mail:
    host: smtp.naver.com               # 네이버 SMTP 서버
    port: 465                          # SSL 포트
    username: nskfn02@naver.com       # 네이버 이메일
    password: QLGVFX36FNC3        # 네이버 앱 비밀번호
    properties:
      mail:
        smtp:
          auth: true                   # SMTP 인증 활성화
          ssl:
            enable: true               # SSL 활성화
            trust: smtp.naver.com      # SSL 신뢰할 SMTP 서버

  # ✅ Redis 설정
  data:
    redis:
      host: localhost
      port: 6379

# ✅ 로깅 설정 (디버깅을 위한 로그 레벨)
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

livekit:
  enabled: false