version: "3.7"

services:
  livekit-server:
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"       # HTTP/WebSocket API
      - "7881:7881/udp"   # UDP Media
    environment:
      - "LIVEKIT_KEYS=878de0038dbed61ed7daab9872fed4e2017e1a37a0b12038a1d62573b64cb4bc: 878de0038dbed61ed7daab9872fed4e2017e1a37a0b12038a1d62573b64cb4bc"   # ✅ 콜론 + 공백, 따옴표 ❌
      - LIVEKIT_API_KEY=878de0038dbed61ed7daab9872fed4e2017e1a37a0b12038a1d62573b64cb4bc                  # ✅ 키는 앞부분
      - LIVEKIT_API_SECRET=878de0038dbed61ed7daab9872fed4e2017e1a37a0b12038a1d62573b64cb4bc               # ✅ 시크릿은 뒷부분 (동일)
      - LIVEKIT_WS_URL=ws://localhost:7880
      - LIVEKIT_LOG_LEVEL=debug
    restart: unless-stopped
